export {
  getIsConnected,
  getK8sClient,
  initK8sClient,
  isK8sAvailable,
} from '@/lib/k8s/client';
export {
  cleanupStuckTerminatingPods,
  createConfigMap,
  createNamespace,
  createSecret,
  deleteConfigMap,
  deleteNamespace,
  deletePod,
  deleteSecret,
  execInPod,
  getConfigMaps,
  getEvents,
  getNodes,
  getPodContainers,
  getPodLogs,
  getPods,
  getPodsAllNamespaces,
  getSecrets,
  getServices,
  upsertConfigMap,
  upsertSecret,
  waitForNamespaceCreated,
  waitForNamespaceDeleted,
} from '@/lib/k8s/core-resources';
export {
  type CloudNativePgClusterManifest,
  createStatefulSet,
  deleteCloudNativePgCluster,
  deleteStatefulSet,
  type StatefulSetEnvFromSecret,
  type StatefulSetEnvVar,
  upsertCloudNativePgCluster,
} from '@/lib/k8s/data-stores';
export {
  type DeploymentSnapshot,
  deploymentExists,
  describeDeploymentRolloutDiagnostics,
  getDeploymentSnapshot,
  verifyServiceReachability,
  waitForDeploymentObserved,
  waitForDeploymentReady,
} from '@/lib/k8s/deployment-diagnostics';
export {
  createDeployment,
  deleteDeployment,
  getDeployments,
  rolloutRestartDeployments,
  scaleDeploymentIfExists,
  updateDeployment,
} from '@/lib/k8s/deployment-resources';
export {
  buildPlatformOperationJob,
  deletePlatformOperationJob,
  ensurePlatformOperationJob,
  getPlatformOperationJobSnapshot,
  getPlatformOperationPodTerminalStatus,
  type PlatformOperationJobInput,
  type PlatformOperationJobSnapshot,
  type PlatformOperationJobStatus,
  submitPlatformOperationJob,
  waitForPlatformOperationJob,
} from '@/lib/k8s/operation-job';
export {
  type CiliumGatewaySpec,
  type CiliumHTTPRouteSpec,
  createCiliumGateway,
  createCiliumHTTPRoute,
  deleteCiliumGateway,
  deleteCiliumHTTPRoute,
  getCiliumGateways,
  getCiliumHTTPRoutes,
  reconcileCiliumHTTPRoutesForHostname,
} from '@/lib/k8s/routing';
export {
  buildServiceResource,
  createService,
  deleteService,
  upsertService,
} from '@/lib/k8s/services';
