apiVersion: v1
kind: Config
clusters:
- cluster:
    server: https://49.232.237.136:6443
    insecure-skip-tls-verify: true
  name: default
contexts:
- context:
    cluster: default
    user: default
  name: default
current-context: default
users:
- name: default
  user:
    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJrVENDQVRlZ0F3SUJBZ0lJZFJzb2pBQng4OFV3Q2dZSUtvWkl6ajBFQXdJd0l6RWhNQjhHQTFVRUF3d1kKYXpOekxXTnNhV1Z1ZEMxallVQXhOelkyTURReE1UTTJNQjRYRFRJMU1USXhPREEyTlRnMU5sb1hEVEkyTVRJeApPREEyTlRnMU5sb3dNREVYTUJVR0ExVUVDaE1PYzNsemRHVnRPbTFoYzNSbGNuTXhGVEFUQmdOVkJBTVRESE41CmMzUmxiVHBoWkcxcGJqQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJEMFU5MW1mTmZhbmxtUTIKeGV1cDYrZ0hXZ1lod01ua2lhZldjbjlpMk5zeWNNUHd6anQ0MEgwaXFxUlF2RnVVeE1XZHhKSGlQMUNRTy9mUApDT1lvMGhPalNEQkdNQTRHQTFVZER3RUIvd1FFQXdJRm9EQVRCZ05WSFNVRUREQUtCZ2dyQmdFRkJRY0RBakFmCkJnTlZIU01FR0RBV2dCUTJjQnNRK2w3WkVNaGVWTW5RNUFEeEI2MFNYakFLQmdncWhrak9QUVFEQWdOSUFEQkYKQWlBb2ZoTzlYdlRmZk1WZ3FjS1NVa3M4eEcveFF4aWpveFQvbU9NalN2c1FXZ0loQU41bUxHamgrdTlPNUYrUQpKTExpQ1pJRm85RWlJWFNsZWRpWGtMRmY4dHRECi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkakNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdFkyeHAKWlc1MExXTmhRREUzTmpZd05ERXhNell3SGhjTk1qVXhNakU0TURZMU9EVTJXaGNOTXpVeE1qRTJNRFkxT0RVMgpXakFqTVNFd0h3WURWUVFEREJock0zTXRZMnhwWlc1MExXTmhRREUzTmpZd05ERXhNell3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFUVC91S0xrQjBNdXFYcE8zQk1rdDlxWVo4QnYyQnBzUVBRdWNCek5heloKdUgvdjNIWGFveVFlZG1mRU10QmdmalFlUXFBeFM4VG9uSkM0NmFEWWJyeVVvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVU5uQWJFUHBlMlJESVhsVEowT1FBCjhRZXRFbDR3Q2dZSUtvWkl6ajBFQXdJRFJ3QXdSQUlnUW5LMGRETEJFU3YyaXRJdHJRQitMbDBVMnBwaTFlQUwKZGdpZDdFYjVDaVFDSUYxQk51a1J1SjJGdjRHQVowTEhtNk9DcnBCbU1mQVFtc2RYbm44aHNBNWUKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    client-key-data: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUYvamRZK1BFYVVvSnRHSEkvUGtUaVJjMHhPU1lBa2NNb1dYUm9rZXQ2Y01vQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFUFJUM1daODE5cWVXWkRiRjY2bnI2QWRhQmlIQXllU0pwOVp5ZjJMWTJ6Snd3L0RPTzNqUQpmU0txcEZDOFc1VEV4WjNFa2VJL1VKQTc5ODhJNWlqU0V3PT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
