apiVersion: juanie.io/v1
kind: ProjectTemplate
metadata:
  name: Next.js 15 App Router
  slug: nextjs-15-app
  version: 1.0.0
  category: fullstack
  tags:
    - nextjs
    - react
    - typescript
    - app-router
    - server-components
    - turbopack
  icon: https://cdn.juanie.io/icons/nextjs.svg
  author:
    name: Juanie Team
    email: team@juanie.io
  license: MIT

spec:
  description: |
    ðŸš€ 2025 å¹´æœ€å‰æ²¿çš„ Next.js 15 å…¨æ ˆåº”ç”¨æ¨¡æ¿
    
    é‡‡ç”¨æœ€æ–°çš„ App Routerã€React Server Componentsã€Server Actions
    é›†æˆ Turbopackã€Tailwind CSS 4ã€shadcn/uiã€Drizzle ORM
    
    å¼€ç®±å³ç”¨çš„ç”Ÿäº§çº§é…ç½®ï¼ŒåŒ…å«è®¤è¯ã€æ•°æ®åº“ã€ç¼“å­˜ã€ç›‘æŽ§ç­‰å®Œæ•´åŠŸèƒ½
  
  # æŠ€æœ¯æ ˆ
  techStack:
    language: TypeScript 5.3
    framework: Next.js 15
    runtime: Node.js 20
    database: PostgreSQL 16
    cache: Redis 7
    orm: Drizzle ORM
    ui: shadcn/ui + Tailwind CSS 4
    auth: NextAuth.js v5
    validation: Zod
    testing: Vitest + Playwright
  
  # ç‰¹æ€§åˆ—è¡¨
  features:
    # Next.js 15 æ–°ç‰¹æ€§
    - "âœ¨ Next.js 15 App Router"
    - "âš¡ Turbopack æž„å»ºï¼ˆå¼€å‘æ¨¡å¼ï¼‰"
    - "ðŸŽ¯ React Server Components"
    - "ðŸ”„ Server Actions"
    - "ðŸ“¦ Partial Prerendering (PPR)"
    - "ðŸŽ¨ Tailwind CSS 4"
    
    # å¼€å‘ä½“éªŒ
    - "ðŸ› ï¸ TypeScript ä¸¥æ ¼æ¨¡å¼"
    - "ðŸ“ ESLint + Prettier"
    - "ðŸŽ­ Playwright E2E æµ‹è¯•"
    - "âš¡ Vitest å•å…ƒæµ‹è¯•"
    - "ðŸ” TypeScript è·¯å¾„åˆ«å"
    
    # UI/UX
    - "ðŸŽ¨ shadcn/ui ç»„ä»¶åº“"
    - "ðŸŒ— æ·±è‰²æ¨¡å¼æ”¯æŒ"
    - "ðŸ“± å“åº”å¼è®¾è®¡"
    - "â™¿ æ— éšœç¢æ”¯æŒ"
    - "ðŸŽ­ Framer Motion åŠ¨ç”»"
    
    # åŽç«¯åŠŸèƒ½
    - "ðŸ” NextAuth.js v5 è®¤è¯"
    - "ðŸ—„ï¸ Drizzle ORM + PostgreSQL"
    - "âš¡ Redis ç¼“å­˜"
    - "ðŸ“§ é‚®ä»¶å‘é€ï¼ˆResendï¼‰"
    - "ðŸ“¤ æ–‡ä»¶ä¸Šä¼ ï¼ˆUploadThingï¼‰"
    
    # æ•°æ®å¤„ç†
    - "âœ… Zod æ•°æ®éªŒè¯"
    - "ðŸ”„ React Query (TanStack Query)"
    - "ðŸ“Š Server Actions è¡¨å•å¤„ç†"
    - "ðŸŽ¯ Optimistic Updates"
    
    # æ€§èƒ½ä¼˜åŒ–
    - "ðŸš€ å›¾ç‰‡ä¼˜åŒ–ï¼ˆnext/imageï¼‰"
    - "ðŸ“¦ ä»£ç åˆ†å‰²"
    - "ðŸ’¾ å¢žé‡é™æ€ç”Ÿæˆï¼ˆISRï¼‰"
    - "âš¡ Edge Runtime æ”¯æŒ"
    - "ðŸ—œï¸ è‡ªåŠ¨åŽ‹ç¼©"
    
    # ç›‘æŽ§å’Œæ—¥å¿—
    - "ðŸ“Š Vercel Analytics"
    - "ðŸ› Sentry é”™è¯¯è¿½è¸ª"
    - "ðŸ“ ç»“æž„åŒ–æ—¥å¿—ï¼ˆPinoï¼‰"
    - "ðŸ“ˆ æ€§èƒ½ç›‘æŽ§"
    
    # DevOps
    - "ðŸ³ Docker å¤šé˜¶æ®µæž„å»º"
    - "ðŸ”„ GitHub Actions CI/CD"
    - "ðŸ“¦ è‡ªåŠ¨ä¾èµ–æ›´æ–°ï¼ˆRenovateï¼‰"
    - "ðŸ”’ å®‰å…¨æ‰«æ"
  
  # é»˜è®¤é…ç½®
  defaults:
    port: 3000
    
    # çŽ¯å¢ƒé…ç½®
    environments:
      - name: dev
        type: development
        replicas: 1
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1Gi
        envVars:
          NODE_ENV: development
          NEXT_TELEMETRY_DISABLED: "1"
          LOG_LEVEL: debug
        gitops:
          enabled: true
          autoSync: true
          gitBranch: develop
          gitPath: overlays/dev
          syncInterval: 1m
      
      - name: staging
        type: staging
        replicas: 2
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 2000m
            memory: 2Gi
        envVars:
          NODE_ENV: production
          NEXT_TELEMETRY_DISABLED: "1"
          LOG_LEVEL: info
        gitops:
          enabled: true
          autoSync: true
          gitBranch: staging
          gitPath: overlays/staging
          syncInterval: 2m
      
      - name: prod
        type: production
        replicas: 3
        resources:
          requests:
            cpu: 1000m
            memory: 2Gi
          limits:
            cpu: 4000m
            memory: 4Gi
        envVars:
          NODE_ENV: production
          NEXT_TELEMETRY_DISABLED: "1"
          LOG_LEVEL: warn
        gitops:
          enabled: true
          autoSync: false
          gitBranch: main
          gitPath: overlays/prod
          syncInterval: 5m
    
    # å¥åº·æ£€æŸ¥
    healthCheck:
      enabled: true
      path: /api/health
      port: 3000
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 3
    
    # GitOps é…ç½®
    gitops:
      enabled: true
      autoSync: true
      syncInterval: 1m
      prune: true
      selfHeal: true
  
  # å¯é…ç½®å‚æ•°
  parameters:
    - name: appName
      displayName: åº”ç”¨åç§°
      description: åº”ç”¨çš„åç§°ï¼Œç”¨äºŽç”Ÿæˆèµ„æºåç§°
      type: string
      required: true
      pattern: ^[a-z0-9-]+$
      example: my-nextjs-app
    
    # Git æä¾›å•†ä¼šè‡ªåŠ¨ä»Žä»“åº“é…ç½®ä¸­èŽ·å–ï¼Œæ— éœ€ç”¨æˆ·æ‰‹åŠ¨é€‰æ‹©
    # gitProvider å’Œ gitlabUrl ä¼šä»Ž repository.provider å’Œ OAuth é…ç½®ä¸­è‡ªåŠ¨æŽ¨æ–­
    
    - name: port
      displayName: ç«¯å£å·
      description: åº”ç”¨ç›‘å¬çš„ç«¯å£
      type: number
      default: 3000
      min: 1024
      max: 65535
    
    - name: enableAuth
      displayName: å¯ç”¨è®¤è¯
      description: æ˜¯å¦åŒ…å« NextAuth.js è®¤è¯é…ç½®
      type: boolean
      default: true
    
    - name: enableDatabase
      displayName: å¯ç”¨æ•°æ®åº“
      description: æ˜¯å¦åŒ…å« PostgreSQL + Drizzle ORM é…ç½®
      type: boolean
      default: true
    
    - name: enableCache
      displayName: å¯ç”¨ç¼“å­˜
      description: æ˜¯å¦åŒ…å« Redis ç¼“å­˜é…ç½®
      type: boolean
      default: true
    
    - name: enableEmail
      displayName: å¯ç”¨é‚®ä»¶
      description: æ˜¯å¦åŒ…å«é‚®ä»¶å‘é€åŠŸèƒ½ï¼ˆResendï¼‰
      type: boolean
      default: false
    
    - name: enableUpload
      displayName: å¯ç”¨æ–‡ä»¶ä¸Šä¼ 
      description: æ˜¯å¦åŒ…å«æ–‡ä»¶ä¸Šä¼ åŠŸèƒ½ï¼ˆUploadThingï¼‰
      type: boolean
      default: false
    
    - name: enableAnalytics
      displayName: å¯ç”¨åˆ†æž
      description: æ˜¯å¦åŒ…å« Vercel Analytics
      type: boolean
      default: true
    
    - name: enableSentry
      displayName: å¯ç”¨é”™è¯¯è¿½è¸ª
      description: æ˜¯å¦åŒ…å« Sentry é”™è¯¯è¿½è¸ª
      type: boolean
      default: true
  
  # æ–‡ä»¶æ˜ å°„
  files:
    app:
      source: ./app
      destination: /
      ignore:
        - node_modules
        - .next
        - .turbo
        - dist
        - .env*.local
    
    k8s:
      source: ./k8s
      destination: /.k8s
    
    ci-github:
      source: ./ci/github-actions.yaml
      destination: /.github/workflows/deploy.yml
      condition: "{{ eq .gitProvider 'github' }}"
    
    ci-gitlab:
      source: ./ci/gitlab-ci.yaml
      destination: /.gitlab-ci.yml
      condition: "{{ or (eq .gitProvider 'gitlab') (eq .gitProvider 'gitlab-self-hosted') }}"
  
  # åˆå§‹åŒ–è„šæœ¬
  hooks:
    preCreate:
      - name: Validate Node.js version
        script: |
          NODE_VERSION=$(node -v | cut -d'v' -f2 | cut -d'.' -f1)
          if [ "$NODE_VERSION" -lt 20 ]; then
            echo "Error: Node.js 20 or higher is required"
            exit 1
          fi
    
    postCreate:
      - name: Install dependencies
        script: |
          cd {{ .projectPath }}
          npm install
      
      - name: Generate Prisma client
        script: |
          cd {{ .projectPath }}
          npm run db:generate
        condition: "{{ .enableDatabase }}"
      
      - name: Setup database
        script: |
          cd {{ .projectPath }}
          npm run db:push
        condition: "{{ .enableDatabase }}"
      
      - name: Run linter
        script: |
          cd {{ .projectPath }}
          npm run lint
      
      - name: Run type check
        script: |
          cd {{ .projectPath }}
          npm run type-check
  
  # æ–‡æ¡£é“¾æŽ¥
  documentation:
    quickStart: ./docs/quick-start.md
    deployment: ./docs/deployment.md
    architecture: ./docs/architecture.md
    api: https://docs.juanie.io/templates/nextjs-15
  
  # ä¾èµ–è¦æ±‚
  requirements:
    node: ">=20.0.0"
    npm: ">=10.0.0"
    docker: ">=24.0.0"
    kubernetes: ">=1.28.0"
    postgresql: ">=16.0.0"
    redis: ">=7.0.0"
