#!/usr/bin/env bash

set -euo pipefail

SSH_OPTS="-o ServerAliveInterval=30 -o ServerAliveCountMax=10 -o TCPKeepAlive=yes"

IMAGE_REPOSITORY="${REGISTRY:?REGISTRY is required}/${IMAGE_NAME:?IMAGE_NAME is required}"
WEB_IMAGE="${IMAGE_REPOSITORY}:web-${GITHUB_SHA}"
WORKER_IMAGE="${IMAGE_REPOSITORY}:worker-${GITHUB_SHA}"
MIGRATE_IMAGE="${IMAGE_REPOSITORY}:migrate-${GITHUB_SHA}"
WEB_IMAGE_TAG="web-${GITHUB_SHA}"
WORKER_IMAGE_TAG="worker-${GITHUB_SHA}"
MIGRATE_IMAGE_TAG="migrate-${GITHUB_SHA}"
CHART_DIR="/tmp/juanie-deploy-${GITHUB_SHA}/juanie"

ssh ${SSH_OPTS} "${SERVER_USER:?SERVER_USER is required}@${SERVER_HOST:?SERVER_HOST is required}" \
  "WEB_IMAGE='${WEB_IMAGE}' WORKER_IMAGE='${WORKER_IMAGE}' MIGRATE_IMAGE='${MIGRATE_IMAGE}' IMAGE_REPOSITORY='${IMAGE_REPOSITORY}' WEB_IMAGE_TAG='${WEB_IMAGE_TAG}' WORKER_IMAGE_TAG='${WORKER_IMAGE_TAG}' MIGRATE_IMAGE_TAG='${MIGRATE_IMAGE_TAG}' CHART_DIR='${CHART_DIR}' bash -s" \
  < .github/scripts/deploy-remote.sh
