installCRDs: true
leaderElect: true
replicaCount: 1

resources:
  requests:
    cpu: 25m
    memory: 64Mi
  limits:
    cpu: 150m
    memory: 192Mi

webhook:
  replicaCount: 1
  resources:
    requests:
      cpu: 20m
      memory: 48Mi
    limits:
      cpu: 100m
      memory: 128Mi

certController:
  replicaCount: 1
  resources:
    requests:
      cpu: 20m
      memory: 48Mi
    limits:
      cpu: 100m
      memory: 128Mi
