// Queue 注入令牌
export const PIPELINE_QUEUE = 'PIPELINE_QUEUE'
export const DEPLOYMENT_QUEUE = 'DEPLOYMENT_QUEUE'
export const REPOSITORY_QUEUE = 'REPOSITORY_QUEUE'
export const PROJECT_INITIALIZATION_QUEUE = 'PROJECT_INITIALIZATION_QUEUE'
