{{- if .Values.monitoring.podMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ .Chart.Name }}-control-plane
  namespace: {{ .Values.monitoring.podMonitor.namespace | default .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    {{- with .Values.monitoring.podMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  namespaceSelector:
    matchNames:
      - {{ .Values.namespace }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
      app.kubernetes.io/component: outbox-dispatcher
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
      interval: {{ .Values.monitoring.podMonitor.interval }}
{{- end }}
