{{- if and (not .Values.secret.existingSecret) (not .Values.externalSecret.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  DATABASE_PASSWORD: "{{ .Values.secret.databasePassword | default "" }}"
  NEXTAUTH_SECRET: "{{ .Values.secret.nextauthSecret | default "" }}"
  NEXTAUTH_URL: "https://{{ .Values.hostname }}"
  GITHUB_CLIENT_ID: "{{ .Values.secret.githubClientId | default "" }}"
  GITHUB_CLIENT_SECRET: "{{ .Values.secret.githubClientSecret | default "" }}"
  GITLAB_CLIENT_ID: "{{ .Values.secret.gitlabClientId | default "" }}"
  GITLAB_CLIENT_SECRET: "{{ .Values.secret.gitlabClientSecret | default "" }}"
  FEISHU_CLIENT_ID: "{{ .Values.secret.feishuClientId | default "" }}"
  FEISHU_CLIENT_SECRET: "{{ .Values.secret.feishuClientSecret | default "" }}"
  AI_302_API_KEY: "{{ .Values.secret.ai302ApiKey | default "" }}"
  ARTIFACT_STORAGE_ACCESS_KEY_ID: "{{ .Values.secret.artifactStorageAccessKeyId | default "" }}"
  ARTIFACT_STORAGE_SECRET_ACCESS_KEY: "{{ .Values.secret.artifactStorageSecretAccessKey | default "" }}"
  ATLAS_DEV_URL: "{{ .Values.secret.atlasDevUrl | default "" }}"
  ATLAS_DEV_URL_POSTGRESQL: "{{ .Values.secret.atlasDevUrlPostgresql | default "" }}"
  ATLAS_DEV_URL_MYSQL: "{{ .Values.secret.atlasDevUrlMysql | default "" }}"
{{- end }}
