{{- $accounts := list "web" "worker" "controller" "scheduler" "outbox" "restate" "backup" -}}
{{- range $index, $account := $accounts }}
{{- if $index }}
---
{{- end }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $.Chart.Name }}-{{ $account }}
  namespace: {{ $.Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ $.Chart.Name }}
    app.kubernetes.io/component: {{ $account }}
{{- with $.Values.imagePullSecrets }}
imagePullSecrets:
  {{- range . }}
  - name: {{ . }}
  {{- end }}
{{- end }}
automountServiceAccountToken: {{ if or (eq $account "controller") (eq $account "scheduler") (and (eq $account "backup") $.Values.backup.restateSnapshot.enabled) }}true{{ else }}false{{ end }}
{{- end }}
