apiVersion: v1
kind: ConfigMap
metadata:
  name: deploy-registry-config
  namespace: juanie
data:
  config.yml: |
    version: 0.1
    log:
      level: info
      formatter: text
      fields:
        service: registry
        environment: production
    storage:
      delete:
        enabled: true
      cache:
        blobdescriptor: inmemory
      filesystem:
        rootdirectory: /var/lib/registry
      tag:
        concurrencylimit: 5
    http:
      addr: :5000
    auth:
      htpasswd:
        realm: Juanie Deploy Registry
        path: /auth/htpasswd
