grafana:
  enabled: false

kubeControllerManager:
  enabled: false

kubeEtcd:
  enabled: false

kubeProxy:
  enabled: false

kubeScheduler:
  enabled: false

kubeStateMetrics:
  enabled: false

prometheus-node-exporter:
  resources:
    requests:
      cpu: 15m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 64Mi

prometheusOperator:
  resources:
    requests:
      cpu: 50m
      memory: 96Mi
    limits:
      cpu: 250m
      memory: 256Mi

prometheus:
  prometheusSpec:
    retention: 7d
    retentionSize: 3GB
    ruleSelectorNilUsesHelmValues: false
    ruleNamespaceSelector: {}
    podMonitorSelectorNilUsesHelmValues: false
    podMonitorNamespaceSelector: {}
    resources:
      requests:
        cpu: 150m
        memory: 384Mi
      limits:
        cpu: 750m
        memory: 768Mi
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: local-path
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 5Gi

alertmanager:
  alertmanagerSpec:
    retention: 120h
    resources:
      requests:
        cpu: 25m
        memory: 64Mi
      limits:
        cpu: 150m
        memory: 128Mi
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: local-path
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
