apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: juanie
  namespace: flux-system
spec:
  interval: 10m0s
  chart:
    spec:
      chart: ./charts/juanie
      sourceRef:
        kind: GitRepository
        name: flux-system
      valuesFiles:
        - ./charts/juanie/values.yaml
        - ./charts/juanie/values-prod.yaml
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values: {}
