import { writeFile } from 'node:fs/promises';

const sha = process.env.GITHUB_SHA;
const registry = process.env.IMAGE_REGISTRY ?? 'ghcr.io';
const repository = process.env.IMAGE_REPOSITORY ?? process.env.GITHUB_REPOSITORY?.toLowerCase();

if (!sha) {
  throw new Error('GITHUB_SHA is required');
}

if (!repository) {
  throw new Error('IMAGE_REPOSITORY or GITHUB_REPOSITORY is required');
}

const imageRepository = `${registry}/${repository}`;
const content = `# Generated by CI. Argo CD reads this file as the platform GitOps promotion pointer.
images:
  web:
    repository: ${imageRepository}
    tag: "web-${sha}"
  runtime:
    repository: ${imageRepository}
    tag: "runtime-${sha}"

schemaSync:
  enabled: true
`;

await writeFile('deploy/k8s/charts/juanie/values-gitops.yaml', content);
