# 生产环境覆盖配置
replicaCount:
  web: 1
  worker: 1
  scheduler: 1

deployment:
  progressDeadlineSeconds: 1200
  revisionHistoryLimit: 3
  web:
    strategy:
      type: RollingUpdate
      maxSurge: 1
      maxUnavailable: 0
  worker:
    strategy:
      type: RollingUpdate
      maxSurge: 1
      maxUnavailable: 0
  scheduler:
    strategy:
      type: Recreate

resources:
  web:
    requests:
      cpu: 100m
      memory: 192Mi
    limits:
      cpu: 500m
      memory: 512Mi
  worker:
    requests:
      cpu: 75m
      memory: 192Mi
    limits:
      cpu: 300m
      memory: 384Mi
  scheduler:
    requests:
      cpu: 25m
      memory: 96Mi
    limits:
      cpu: 150m
      memory: 192Mi
