# 生产环境覆盖配置
replicaCount:
  web: 1
  worker: 1
  scheduler: 1

deployment:
  progressDeadlineSeconds: 1200
  revisionHistoryLimit: 3
  web:
    strategy:
      type: RollingUpdate
      maxSurge: 1
      maxUnavailable: 0
  worker:
    strategy:
      type: RollingUpdate
      maxSurge: 1
      maxUnavailable: 0
  scheduler:
    strategy:
      type: Recreate

resources:
  web:
    requests:
      cpu: 100m
      memory: 192Mi
    limits:
      cpu: 500m
      memory: 512Mi
  worker:
    requests:
      cpu: 75m
      memory: 192Mi
    limits:
      cpu: 300m
      memory: 384Mi
  scheduler:
    requests:
      cpu: 25m
      memory: 96Mi
    limits:
      cpu: 150m
      memory: 192Mi

env:
  JUANIE_BASE_DOMAIN: "juanie.art"
  JUANIE_ARGOCD_NAMESPACE: "argocd"
  JUANIE_ARGOCD_PROJECT: "juanie"
  JUANIE_ARGOCD_DESTINATION_SERVER: "https://kubernetes.default.svc"
  JUANIE_PREVIEW_APPLICATIONSET_ENABLED: "true"
  JUANIE_PREVIEW_APPLICATIONSET_REPO_URL: "https://github.com/997899594/Juanie.git"
  JUANIE_PREVIEW_APPLICATIONSET_TARGET_REVISION: "main"
  JUANIE_PREVIEW_APPLICATIONSET_PATH: "deploy/k8s/charts/preview-scaffold"
