import { execFile } from 'node:child_process';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { promisify } from 'node:util';
import type { V1Job } from '@kubernetes/client-node';
import { and, eq, inArray } from 'drizzle-orm';
import { createAuditLog } from '@/lib/audit';
import { db } from '@/lib/db';
import { projects, schemaRepairAtlasRuns, schemaRepairPlans } from '@/lib/db/schema';
import { getTeamIntegrationSession } from '@/lib/integrations/service/integration-control-plane';
import { createJob, deleteJob, isK8sAvailable } from '@/lib/k8s';
import { resolveMigrationPath } from '@/lib/migrations/path';
import { publishSchemaRepairRealtimeSnapshot } from '@/lib/realtime/schema-repairs';
import {
  buildWorkspaceDiffSummary,
  collectWorkspaceArtifactFiles,
  collectWorkspaceFileSnapshot,
  createRepositorySourceWorkspace,
} from '@/lib/repositories/source-workspace';
import { resolveSchemaManagementSpec } from '@/lib/schema-management/inspect';
import { buildSchemaRepairRuntimeArtifacts } from '@/lib/schema-management/review-request-helpers';
import {
  buildSchemaRunnerJob,
  resolveSchemaRunnerImage,
} from '@/lib/schema-management/schema-runner-job';

const execFileAsync = promisify(execFile);

async function runCommand(
  command: string,
  args: string[],
  options?: { cwd?: string; env?: NodeJS.ProcessEnv }
) {
  const result = await execFileAsync(command, args, {
    cwd: options?.cwd,
    env: options?.env,
    maxBuffer: 10 * 1024 * 1024,
  });

  return `${result.stdout ?? ''}${result.stderr ?? ''}`.trim();
}

function clipLog(value: string): string {
  return value.slice(-12000);
}

async function fileExists(pathname: string): Promise<boolean> {
  try {
    await readFile(pathname, 'utf8');
    return true;
  } catch {
    return false;
  }
}

async function assertAtlasGeneratedQuality(input: {
  repoDir: string;
  changedFiles: string[];
}): Promise<void> {
  const migrationFiles = input.changedFiles.filter((file) => file.endsWith('.sql'));

  if (migrationFiles.length === 0) {
    throw new Error('Atlas 未生成任何 migration SQL 文件');
  }

  for (const file of migrationFiles) {
    const absolutePath = path.join(input.repoDir, file);
    if (!(await fileExists(absolutePath))) {
      continue;
    }

    const content = await readFile(absolutePath, 'utf8');
    if (
      content.includes('Generated by Juanie schema management') ||
      content.includes('JUANIE_REPAIR_SCAFFOLD') ||
      content.includes('RAISE EXCEPTION')
    ) {
      throw new Error(`Atlas 结果仍包含 scaffold 占位内容: ${file}`);
    }
  }
}

export async function runSchemaRepairAtlas(input: {
  projectId: string;
  planId: string;
  userId: string;
}) {
  const run = await createSchemaRepairAtlasRun(input);
  return run;
}

function buildSchemaRepairJobName(atlasRunId: string): string {
  return `schema-repair-${atlasRunId.slice(0, 8)}`;
}

function buildSchemaRepairDraftJob(input: {
  namespace: string;
  jobName: string;
  image: string;
  atlasRunId: string;
  projectId: string;
  userId: string | null;
}) {
  return buildSchemaRunnerJob({
    namespace: input.namespace,
    jobName: input.jobName,
    image: input.image,
    mode: 'schema-repair',
    labels: {
      'juanie.dev/schema-repair-run-id': input.atlasRunId,
    },
    env: [
      {
        name: 'SCHEMA_REPAIR_ATLAS_RUN_ID',
        value: input.atlasRunId,
      },
      {
        name: 'SCHEMA_REPAIR_PROJECT_ID',
        value: input.projectId,
      },
      {
        name: 'SCHEMA_REPAIR_USER_ID',
        value: input.userId ?? '',
      },
    ],
  }) satisfies V1Job;
}

export async function createSchemaRepairAtlasRun(input: {
  projectId: string;
  planId: string;
  userId: string;
}) {
  const project = await db.query.projects.findFirst({
    where: eq(projects.id, input.projectId),
    with: {
      repository: true,
    },
  });

  if (!project?.repository) {
    throw new Error('项目缺少仓库绑定');
  }

  const plan = await db.query.schemaRepairPlans.findFirst({
    where: eq(schemaRepairPlans.id, input.planId),
    with: {
      database: true,
    },
  });

  if (!plan || plan.projectId !== input.projectId) {
    throw new Error('修复计划不存在');
  }

  const activeRun = await db.query.schemaRepairAtlasRuns.findFirst({
    where: and(
      eq(schemaRepairAtlasRuns.projectId, input.projectId),
      eq(schemaRepairAtlasRuns.databaseId, plan.databaseId),
      inArray(schemaRepairAtlasRuns.status, ['queued', 'running'])
    ),
    orderBy: (table, { desc }) => [desc(table.createdAt)],
  });

  if (activeRun) {
    if (activeRun.status === 'queued') {
      const requeuedAt = new Date();
      const jobName = activeRun.jobName ?? buildSchemaRepairJobName(activeRun.id);
      const namespace = process.env.JUANIE_NAMESPACE ?? 'juanie';
      const schemaRunnerImage = resolveSchemaRunnerImage();

      if (!isK8sAvailable()) {
        throw new Error('Schema runner draft execution requires Kubernetes connectivity');
      }
      if (!schemaRunnerImage) {
        throw new Error('SCHEMA_RUNNER_IMAGE_REPOSITORY and SCHEMA_RUNNER_IMAGE_TAG are required');
      }

      await db
        .update(schemaRepairPlans)
        .set({
          atlasExecutionStatus: 'queued',
          atlasExecutionStartedAt: null,
          atlasExecutionFinishedAt: null,
          atlasExecutionLog: null,
          errorMessage: null,
          updatedAt: requeuedAt,
        })
        .where(eq(schemaRepairPlans.id, plan.id));

      await db
        .update(schemaRepairAtlasRuns)
        .set({
          status: 'queued',
          jobName,
          errorMessage: null,
          log: null,
          finishedAt: null,
          updatedAt: requeuedAt,
        })
        .where(eq(schemaRepairAtlasRuns.id, activeRun.id));
      await publishSchemaRepairRealtimeSnapshot({
        projectId: input.projectId,
        databaseId: plan.databaseId,
      });

      try {
        await deleteJob(namespace, jobName).catch(() => undefined);
        await createJob(
          namespace,
          buildSchemaRepairDraftJob({
            namespace,
            jobName,
            image: schemaRunnerImage,
            atlasRunId: activeRun.id,
            projectId: input.projectId,
            userId: input.userId,
          })
        );
      } catch (error) {
        const message = error instanceof Error ? error.message : String(error);
        const failedAt = new Date();

        await db
          .update(schemaRepairPlans)
          .set({
            atlasExecutionStatus: 'failed',
            atlasExecutionFinishedAt: failedAt,
            atlasExecutionLog: message,
            errorMessage: message,
            updatedAt: failedAt,
          })
          .where(eq(schemaRepairPlans.id, plan.id));

        await db
          .update(schemaRepairAtlasRuns)
          .set({
            status: 'failed',
            log: message,
            errorMessage: message,
            finishedAt: failedAt,
            updatedAt: failedAt,
          })
          .where(eq(schemaRepairAtlasRuns.id, activeRun.id));
        await publishSchemaRepairRealtimeSnapshot({
          projectId: input.projectId,
          databaseId: plan.databaseId,
        });

        throw error;
      }
    }

    return activeRun;
  }

  const queuedAt = new Date();
  const namespace = process.env.JUANIE_NAMESPACE ?? 'juanie';
  const schemaRunnerImage = resolveSchemaRunnerImage();

  if (!isK8sAvailable()) {
    throw new Error('Schema runner draft execution requires Kubernetes connectivity');
  }
  if (!schemaRunnerImage) {
    throw new Error('SCHEMA_RUNNER_IMAGE_REPOSITORY and SCHEMA_RUNNER_IMAGE_TAG are required');
  }

  const [run] = await db
    .insert(schemaRepairAtlasRuns)
    .values({
      planId: plan.id,
      projectId: input.projectId,
      environmentId: plan.environmentId,
      databaseId: plan.databaseId,
      status: 'queued',
    })
    .returning();
  const jobName = buildSchemaRepairJobName(run.id);

  await db
    .update(schemaRepairAtlasRuns)
    .set({
      jobName,
      updatedAt: queuedAt,
    })
    .where(eq(schemaRepairAtlasRuns.id, run.id));

  await db
    .update(schemaRepairPlans)
    .set({
      atlasExecutionStatus: 'queued',
      atlasExecutionStartedAt: null,
      atlasExecutionFinishedAt: null,
      atlasExecutionLog: null,
      updatedAt: queuedAt,
    })
    .where(eq(schemaRepairPlans.id, plan.id));

  try {
    await deleteJob(namespace, jobName).catch(() => undefined);
    await createJob(
      namespace,
      buildSchemaRepairDraftJob({
        namespace,
        jobName,
        image: schemaRunnerImage,
        atlasRunId: run.id,
        projectId: input.projectId,
        userId: input.userId,
      })
    );
    await publishSchemaRepairRealtimeSnapshot({
      projectId: input.projectId,
      databaseId: plan.databaseId,
    });
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    const failedAt = new Date();

    await db
      .update(schemaRepairPlans)
      .set({
        atlasExecutionStatus: 'failed',
        atlasExecutionFinishedAt: failedAt,
        atlasExecutionLog: message,
        errorMessage: message,
        updatedAt: failedAt,
      })
      .where(eq(schemaRepairPlans.id, plan.id));

    await db
      .update(schemaRepairAtlasRuns)
      .set({
        status: 'failed',
        log: message,
        errorMessage: message,
        finishedAt: failedAt,
        updatedAt: failedAt,
      })
      .where(eq(schemaRepairAtlasRuns.id, run.id));
    await publishSchemaRepairRealtimeSnapshot({
      projectId: input.projectId,
      databaseId: plan.databaseId,
    });

    throw error;
  }

  return run;
}

export async function executeSchemaRepairAtlasRun(input: {
  atlasRunId: string;
  projectId: string;
  userId?: string | null;
}) {
  const run = await db.query.schemaRepairAtlasRuns.findFirst({
    where: eq(schemaRepairAtlasRuns.id, input.atlasRunId),
  });

  if (!run || run.projectId !== input.projectId) {
    throw new Error('Atlas 执行记录不存在');
  }

  const project = await db.query.projects.findFirst({
    where: eq(projects.id, input.projectId),
    with: {
      repository: true,
    },
  });

  if (!project?.repository) {
    throw new Error('项目缺少仓库绑定');
  }

  const plan = await db.query.schemaRepairPlans.findFirst({
    where: eq(schemaRepairPlans.id, run.planId),
    with: {
      database: true,
    },
  });

  if (!plan) {
    throw new Error('修复计划不存在');
  }

  const session = await getTeamIntegrationSession({
    teamId: project.teamId,
    actingUserId: input.userId ?? null,
    requiredCapabilities: ['read_repo', 'write_repo'],
  });

  const baseBranch = project.repository.defaultBranch || 'main';
  const startTime = new Date();
  await db
    .update(schemaRepairPlans)
    .set({
      atlasExecutionStatus: 'running',
      atlasExecutionStartedAt: startTime,
      atlasExecutionFinishedAt: null,
      atlasExecutionLog: null,
      updatedAt: startTime,
    })
    .where(eq(schemaRepairPlans.id, plan.id));
  await db
    .update(schemaRepairAtlasRuns)
    .set({
      status: 'running',
      startedAt: startTime,
      updatedAt: startTime,
    })
    .where(eq(schemaRepairAtlasRuns.id, run.id));
  await publishSchemaRepairRealtimeSnapshot({
    projectId: input.projectId,
    databaseId: plan.databaseId,
  });

  try {
    let logs = '';
    const workspace = await createRepositorySourceWorkspace({
      session,
      repoFullName: project.repository.fullName,
      defaultBranch: baseBranch,
      revision: baseBranch,
    });
    const repoDir = workspace.repoDir;
    const initialSnapshot = await collectWorkspaceFileSnapshot(repoDir);

    try {
      const spec = await resolveSchemaManagementSpec({
        projectId: input.projectId,
        databaseId: plan.databaseId,
      });

      if (!spec) {
        throw new Error('无法解析 schema repair 对应的迁移配置');
      }

      const migrationPath =
        spec.specification.tool === 'drizzle'
          ? '.juanie/schema-repair/generated'
          : resolveMigrationPath(spec.specification, spec.database.type);
      if (!migrationPath) {
        throw new Error('当前迁移工具没有可用的 migration 目录，无法运行 Atlas');
      }

      const runtimeArtifacts = buildSchemaRepairRuntimeArtifacts({
        provider: session.provider,
        tool: spec.specification.tool,
        databaseType: spec.database.type,
        migrationPath,
        planId: plan.id,
        title: plan.title,
        summary: plan.summary,
        planKind: plan.kind,
        stateStatus: plan.stateStatus,
        databaseName: plan.database?.name ?? 'database',
        expectedVersion: plan.expectedVersion,
        actualVersion: plan.actualVersion,
        sourceConfigPath: spec.specification.sourceConfigPath,
      });
      const runtimeDir = path.join(repoDir, '.juanie', 'schema-repair');
      await mkdir(runtimeDir, { recursive: true });
      await Promise.all(
        Object.entries(runtimeArtifacts.files).map(([relativePath, content]) =>
          writeFile(path.join(repoDir, relativePath), content, 'utf8')
        )
      );
      const scriptPath = path.join(repoDir, runtimeArtifacts.atlasScriptPath);

      const env = {
        ...process.env,
        ATLAS_DEV_URL: process.env.ATLAS_DEV_URL ?? 'docker://postgres/16/dev',
        ATLAS_SRC_URL:
          plan.kind === 'adopt_current_db'
            ? (plan.database?.connectionString ?? '')
            : process.env.ATLAS_SRC_URL,
      };

      logs += await runCommand('bash', [scriptPath], {
        cwd: repoDir,
        env,
      });
      logs += '\n';

      const diffSummary = buildWorkspaceDiffSummary(
        initialSnapshot,
        await collectWorkspaceFileSnapshot(repoDir)
      );
      await assertAtlasGeneratedQuality({
        repoDir,
        changedFiles: diffSummary.changedFiles,
      });
      if (diffSummary.changedFiles.length > 0) {
        logs += diffSummary.changedFiles.map((file) => `M ${file}`).join('\n');
        logs += '\n';
        const artifactFiles = await collectWorkspaceArtifactFiles(
          repoDir,
          diffSummary.changedFiles
        );
        const finishedAt = new Date();
        const [updated] = await db
          .update(schemaRepairPlans)
          .set({
            atlasExecutionStatus: 'succeeded',
            atlasExecutionLog: clipLog(logs),
            atlasExecutionFinishedAt: finishedAt,
            updatedAt: finishedAt,
          })
          .where(eq(schemaRepairPlans.id, plan.id))
          .returning();
        await db
          .update(schemaRepairAtlasRuns)
          .set({
            status: 'succeeded',
            generatedFiles: diffSummary.changedFiles,
            artifactFiles,
            diffSummary,
            commitSha: null,
            log: clipLog(logs),
            finishedAt,
            updatedAt: finishedAt,
          })
          .where(eq(schemaRepairAtlasRuns.id, run.id));
        await publishSchemaRepairRealtimeSnapshot({
          projectId: input.projectId,
          databaseId: plan.databaseId,
        });

        await createAuditLog({
          teamId: project.teamId,
          userId: input.userId ?? undefined,
          action: 'project.updated',
          resourceType: 'project',
          resourceId: project.id,
          metadata: {
            schemaAction: 'run_atlas_draft',
            databaseId: plan.databaseId,
            planId: plan.id,
            atlasRunId: run.id,
          },
        });

        return updated;
      }

      throw new Error('Atlas 执行完成但没有产生任何文件变更');
    } finally {
      await workspace.cleanup();
    }
  } catch (error) {
    const finishedAt = new Date();
    const message = error instanceof Error ? error.message : String(error);
    await db
      .update(schemaRepairPlans)
      .set({
        atlasExecutionStatus: 'failed',
        atlasExecutionLog: clipLog(message),
        atlasExecutionFinishedAt: finishedAt,
        errorMessage: message,
        updatedAt: finishedAt,
      })
      .where(eq(schemaRepairPlans.id, plan.id));
    await db
      .update(schemaRepairAtlasRuns)
      .set({
        status: 'failed',
        log: clipLog(message),
        errorMessage: message,
        finishedAt,
        updatedAt: finishedAt,
      })
      .where(eq(schemaRepairAtlasRuns.id, run.id));
    await publishSchemaRepairRealtimeSnapshot({
      projectId: input.projectId,
      databaseId: plan.databaseId,
    });
    throw error;
  }
}
