import { execFile } from 'node:child_process';
import { mkdtemp, readFile, rm } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { promisify } from 'node:util';
import { and, eq, inArray } from 'drizzle-orm';
import { createAuditLog } from '@/lib/audit';
import { db } from '@/lib/db';
import { projects, schemaRepairAtlasRuns, schemaRepairPlans } from '@/lib/db/schema';
import { getTeamIntegrationSession } from '@/lib/integrations/service/integration-control-plane';
import { addSchemaRepairAtlasJob } from '@/lib/queue';

const execFileAsync = promisify(execFile);

function buildAuthenticatedCloneUrl(input: {
  cloneUrl: string | null;
  fullName: string;
  provider: 'github' | 'gitlab' | 'gitlab-self-hosted';
  accessToken: string;
}): string {
  const fallbackUrl =
    input.cloneUrl ??
    (input.provider === 'github'
      ? `https://github.com/${input.fullName}.git`
      : `https://gitlab.com/${input.fullName}.git`);
  const url = new URL(fallbackUrl);

  if (input.provider === 'github') {
    url.username = 'x-access-token';
    url.password = input.accessToken;
  } else {
    url.username = 'oauth2';
    url.password = input.accessToken;
  }

  return url.toString();
}

async function runCommand(
  command: string,
  args: string[],
  options?: { cwd?: string; env?: NodeJS.ProcessEnv }
) {
  const result = await execFileAsync(command, args, {
    cwd: options?.cwd,
    env: options?.env,
    maxBuffer: 10 * 1024 * 1024,
  });

  return `${result.stdout ?? ''}${result.stderr ?? ''}`.trim();
}

function clipLog(value: string): string {
  return value.slice(-12000);
}

async function fileExists(pathname: string): Promise<boolean> {
  try {
    await readFile(pathname, 'utf8');
    return true;
  } catch {
    return false;
  }
}

async function restoreGeneratedFilesToBase(
  repoDir: string,
  baseBranch: string,
  generatedFiles: string[]
): Promise<void> {
  for (const file of generatedFiles) {
    if (
      !(file.endsWith('.sql') || file.endsWith('_journal.json') || file.endsWith('.schema.sql'))
    ) {
      continue;
    }

    let hasBaseVersion = true;
    try {
      await runCommand('git', ['cat-file', '-e', `origin/${baseBranch}:${file}`], { cwd: repoDir });
    } catch {
      hasBaseVersion = false;
    }

    if (hasBaseVersion) {
      await runCommand('git', ['checkout', `origin/${baseBranch}`, '--', file], { cwd: repoDir });
      continue;
    }

    await runCommand('rm', ['-f', file], { cwd: repoDir }).catch(() => {});
  }
}

async function collectDiffSummary(repoDir: string) {
  const diffNamesRaw = await runCommand('git', ['diff', '--name-only'], { cwd: repoDir });
  const diffStatsRaw = await runCommand('git', ['diff', '--numstat'], { cwd: repoDir });
  const changedFiles = diffNamesRaw
    .split('\n')
    .map((line) => line.trim())
    .filter(Boolean);
  const fileStats = diffStatsRaw
    .split('\n')
    .map((line) => line.trim())
    .filter(Boolean)
    .map((line) => {
      const [added, removed, file] = line.split('\t');
      return {
        file,
        added: Number.parseInt(added ?? '0', 10) || 0,
        removed: Number.parseInt(removed ?? '0', 10) || 0,
      };
    });

  return {
    changedFiles,
    fileStats,
  };
}

async function assertAtlasGeneratedQuality(input: {
  repoDir: string;
  changedFiles: string[];
}): Promise<void> {
  const migrationFiles = input.changedFiles.filter((file) => file.endsWith('.sql'));

  if (migrationFiles.length === 0) {
    throw new Error('Atlas 未生成任何 migration SQL 文件');
  }

  for (const file of migrationFiles) {
    const absolutePath = path.join(input.repoDir, file);
    if (!(await fileExists(absolutePath))) {
      continue;
    }

    const content = await readFile(absolutePath, 'utf8');
    if (
      content.includes('Generated by Juanie schema management') ||
      content.includes('JUANIE_REPAIR_SCAFFOLD') ||
      content.includes('RAISE EXCEPTION')
    ) {
      throw new Error(`Atlas 结果仍包含 scaffold 占位内容: ${file}`);
    }
  }
}

export async function runSchemaRepairAtlas(input: {
  projectId: string;
  planId: string;
  userId: string;
}) {
  const run = await createSchemaRepairAtlasRun(input);
  return run;
}

export async function createSchemaRepairAtlasRun(input: {
  projectId: string;
  planId: string;
  userId: string;
}) {
  const project = await db.query.projects.findFirst({
    where: eq(projects.id, input.projectId),
    with: {
      repository: true,
    },
  });

  if (!project?.repository) {
    throw new Error('项目缺少仓库绑定');
  }

  const plan = await db.query.schemaRepairPlans.findFirst({
    where: eq(schemaRepairPlans.id, input.planId),
    with: {
      database: true,
    },
  });

  if (!plan || plan.projectId !== input.projectId) {
    throw new Error('修复计划不存在');
  }

  if (!plan.branchName) {
    throw new Error('修复计划还没有 branch');
  }

  const activeRun = await db.query.schemaRepairAtlasRuns.findFirst({
    where: and(
      eq(schemaRepairAtlasRuns.projectId, input.projectId),
      eq(schemaRepairAtlasRuns.databaseId, plan.databaseId),
      inArray(schemaRepairAtlasRuns.status, ['queued', 'running'])
    ),
    orderBy: (table, { desc }) => [desc(table.createdAt)],
  });

  if (activeRun) {
    return activeRun;
  }

  const queuedAt = new Date();
  const [run] = await db
    .insert(schemaRepairAtlasRuns)
    .values({
      planId: plan.id,
      projectId: input.projectId,
      environmentId: plan.environmentId,
      databaseId: plan.databaseId,
      status: 'queued',
    })
    .returning();

  await db
    .update(schemaRepairPlans)
    .set({
      atlasExecutionStatus: 'queued',
      atlasExecutionStartedAt: null,
      atlasExecutionFinishedAt: null,
      atlasExecutionLog: null,
      updatedAt: queuedAt,
    })
    .where(eq(schemaRepairPlans.id, plan.id));

  await addSchemaRepairAtlasJob(run.id, input.projectId, input.userId);

  return run;
}

export async function executeSchemaRepairAtlasRun(input: {
  atlasRunId: string;
  projectId: string;
  userId?: string | null;
}) {
  const run = await db.query.schemaRepairAtlasRuns.findFirst({
    where: eq(schemaRepairAtlasRuns.id, input.atlasRunId),
  });

  if (!run || run.projectId !== input.projectId) {
    throw new Error('Atlas 执行记录不存在');
  }

  const project = await db.query.projects.findFirst({
    where: eq(projects.id, input.projectId),
    with: {
      repository: true,
    },
  });

  if (!project?.repository) {
    throw new Error('项目缺少仓库绑定');
  }

  const plan = await db.query.schemaRepairPlans.findFirst({
    where: eq(schemaRepairPlans.id, run.planId),
    with: {
      database: true,
    },
  });

  if (!plan) {
    throw new Error('修复计划不存在');
  }
  if (!plan.branchName) {
    throw new Error('修复计划还没有 branch');
  }

  const session = await getTeamIntegrationSession({
    teamId: project.teamId,
    actingUserId: input.userId ?? null,
    requiredCapabilities: ['write_repo'],
  });

  const tempRoot = await mkdtemp(path.join(os.tmpdir(), 'juanie-schema-repair-'));
  const repoDir = path.join(tempRoot, 'repo');
  const cloneUrl = buildAuthenticatedCloneUrl({
    cloneUrl: project.repository.cloneUrl ?? null,
    fullName: project.repository.fullName,
    provider: session.provider,
    accessToken: session.accessToken,
  });
  const baseBranch = project.repository.defaultBranch || 'main';
  const branchName = plan.branchName;
  const scriptPath = path.join(repoDir, '.juanie', 'schema-repair', `${plan.id}.atlas.sh`);
  const startTime = new Date();
  await db
    .update(schemaRepairPlans)
    .set({
      atlasExecutionStatus: 'running',
      atlasExecutionStartedAt: startTime,
      atlasExecutionFinishedAt: null,
      atlasExecutionLog: null,
      updatedAt: startTime,
    })
    .where(eq(schemaRepairPlans.id, plan.id));
  await db
    .update(schemaRepairAtlasRuns)
    .set({
      status: 'running',
      startedAt: startTime,
      updatedAt: startTime,
    })
    .where(eq(schemaRepairAtlasRuns.id, run.id));

  try {
    let logs = '';

    logs += await runCommand('git', [
      'clone',
      '--depth',
      '1',
      '--branch',
      branchName,
      cloneUrl,
      repoDir,
    ]);
    logs += '\n';
    await runCommand('git', ['fetch', 'origin', baseBranch, '--depth', '1'], { cwd: repoDir });
    await restoreGeneratedFilesToBase(
      repoDir,
      baseBranch,
      Array.isArray(plan.generatedFiles) ? (plan.generatedFiles as string[]) : []
    );

    const env = {
      ...process.env,
      ATLAS_DEV_URL: process.env.ATLAS_DEV_URL ?? 'docker://postgres/16/dev',
      ATLAS_SRC_URL:
        plan.kind === 'adopt_current_db'
          ? (plan.database?.connectionString ?? '')
          : process.env.ATLAS_SRC_URL,
    };

    logs += await runCommand('bash', [scriptPath], {
      cwd: repoDir,
      env,
    });
    logs += '\n';

    const status = await runCommand('git', ['status', '--short'], { cwd: repoDir });
    const diffSummary = await collectDiffSummary(repoDir);
    await assertAtlasGeneratedQuality({
      repoDir,
      changedFiles: diffSummary.changedFiles,
    });
    if (status.trim().length > 0) {
      logs += status;
      logs += '\n';
      await runCommand('git', ['config', 'user.name', 'Juanie Bot'], { cwd: repoDir });
      await runCommand('git', ['config', 'user.email', 'noreply@juanie.art'], { cwd: repoDir });
      await runCommand('git', ['add', '.'], { cwd: repoDir });
      await runCommand(
        'git',
        ['commit', '-m', `chore: run atlas schema repair for ${plan.database?.name ?? 'database'}`],
        { cwd: repoDir }
      );
      const commitSha = await runCommand('git', ['rev-parse', 'HEAD'], { cwd: repoDir });
      await runCommand('git', ['push', 'origin', branchName], { cwd: repoDir });
      const finishedAt = new Date();
      const [updated] = await db
        .update(schemaRepairPlans)
        .set({
          atlasExecutionStatus: 'succeeded',
          atlasExecutionLog: clipLog(logs),
          atlasExecutionFinishedAt: finishedAt,
          updatedAt: finishedAt,
        })
        .where(eq(schemaRepairPlans.id, plan.id))
        .returning();
      await db
        .update(schemaRepairAtlasRuns)
        .set({
          status: 'succeeded',
          generatedFiles: diffSummary.changedFiles,
          diffSummary,
          commitSha,
          log: clipLog(logs),
          finishedAt,
          updatedAt: finishedAt,
        })
        .where(eq(schemaRepairAtlasRuns.id, run.id));

      await createAuditLog({
        teamId: project.teamId,
        userId: input.userId ?? undefined,
        action: 'project.updated',
        resourceType: 'project',
        resourceId: project.id,
        metadata: {
          schemaAction: 'run_atlas_repair',
          databaseId: plan.databaseId,
          planId: plan.id,
          branchName,
          atlasRunId: run.id,
        },
      });

      return updated;
    }

    throw new Error('Atlas 执行完成但没有产生任何文件变更');
  } catch (error) {
    const finishedAt = new Date();
    const message = error instanceof Error ? error.message : String(error);
    await db
      .update(schemaRepairPlans)
      .set({
        atlasExecutionStatus: 'failed',
        atlasExecutionLog: clipLog(message),
        atlasExecutionFinishedAt: finishedAt,
        errorMessage: message,
        updatedAt: finishedAt,
      })
      .where(eq(schemaRepairPlans.id, plan.id));
    await db
      .update(schemaRepairAtlasRuns)
      .set({
        status: 'failed',
        log: clipLog(message),
        errorMessage: message,
        finishedAt,
        updatedAt: finishedAt,
      })
      .where(eq(schemaRepairAtlasRuns.id, run.id));
    throw error;
  } finally {
    await rm(tempRoot, { recursive: true, force: true }).catch(() => {});
  }
}
