export interface GeneratedSchemaRepairArtifacts {
  files: Record<string, string>;
  generatedFiles: string[];
  migrationTag: string | null;
}

export interface SchemaRepairRuntimeArtifacts {
  files: Record<string, string>;
  atlasConfigPath: string;
  atlasScriptPath: string;
}

interface SchemaRepairArtifactInput {
  provider: 'github' | 'gitlab' | 'gitlab-self-hosted';
  tool: 'atlas' | 'drizzle' | 'sql' | 'prisma' | 'knex' | 'typeorm' | 'custom';
  databaseType: 'postgresql' | 'mysql' | 'redis' | 'mongodb';
  migrationPath: string | null;
  existingMigrationNames: string[];
  journalContent?: string | null;
  planId: string;
  title: string;
  summary: string;
  planKind:
    | 'no_action'
    | 'run_release_migrations'
    | 'mark_aligned'
    | 'repair_pr_required'
    | 'adopt_current_db'
    | 'manual_investigation';
  stateStatus: string;
  databaseName: string;
  expectedVersion: string | null;
  actualVersion: string | null;
}

function parseNumericPrefix(value: string): number | null {
  const match = value.match(/^(\d+)_/u);
  if (!match?.[1]) {
    return null;
  }

  return Number.parseInt(match[1], 10);
}

export function buildNextMigrationTag(existingNames: string[], stem: string): string {
  const parsed = existingNames
    .map((name) => name.replace(/\.(sql|js)$/u, ''))
    .map((name) => ({
      name,
      prefix: parseNumericPrefix(name),
    }))
    .filter((item) => item.prefix !== null);

  const maxPrefix = parsed.reduce((current, item) => Math.max(current, item.prefix ?? 0), -1);
  const width = parsed.reduce((current, item) => {
    const match = item.name.match(/^(\d+)_/u);
    return Math.max(current, match?.[1]?.length ?? 4);
  }, 4);

  return `${String(maxPrefix + 1).padStart(width, '0')}_${stem}`;
}

export function appendDrizzleJournalEntry(
  journalContent: string | null | undefined,
  tag: string,
  when: number
): string {
  const journal = journalContent
    ? (JSON.parse(journalContent) as {
        version?: string;
        dialect?: string;
        entries?: Array<{
          idx?: unknown;
          version?: unknown;
          when?: unknown;
          tag?: unknown;
          breakpoints?: unknown;
        }>;
      })
    : {};

  const version = typeof journal.version === 'string' ? journal.version : '7';
  const dialect = typeof journal.dialect === 'string' ? journal.dialect : 'postgresql';
  const existingEntries = Array.isArray(journal.entries) ? journal.entries : [];
  const nextIdx =
    existingEntries.reduce((current, entry) => {
      const idx = typeof entry?.idx === 'number' ? entry.idx : -1;
      return Math.max(current, idx);
    }, -1) + 1;

  const next = {
    version,
    dialect,
    entries: [
      ...existingEntries,
      {
        idx: nextIdx,
        version,
        when,
        tag,
        breakpoints: true,
      },
    ],
  };

  return `${JSON.stringify(next, null, 2)}\n`;
}

function buildFailureScaffoldMessage(input: SchemaRepairArtifactInput): string {
  return [
    `Generated by Juanie schema management.`,
    `Plan: ${input.planId}`,
    `Kind: ${input.planKind}`,
    `Database: ${input.databaseName}`,
    `Expected: ${input.expectedVersion ?? 'unknown'}`,
    `Actual: ${input.actualVersion ?? 'unknown'}`,
    `Title: ${input.title}`,
    `Summary: ${input.summary}`,
    `Replace this scaffold with the real repair migration before merge.`,
  ].join(' | ');
}

function buildAtlasConfigContent(input: SchemaRepairArtifactInput): string {
  const schemaFilePath = `.juanie/schema-repair/${input.planId}.schema.sql`;
  const envBlock =
    input.tool === 'drizzle'
      ? [
          `env "repair" {`,
          `  src = "file://${schemaFilePath}"`,
          `  dev = env("ATLAS_DEV_URL")`,
          `  migration {`,
          `    dir = "file://${input.migrationPath}"`,
          `  }`,
          `}`,
          ``,
        ]
      : [
          `env "repair" {`,
          `  src = env("ATLAS_SRC_URL")`,
          `  dev = env("ATLAS_DEV_URL")`,
          `  migration {`,
          `    dir = "file://${input.migrationPath}"`,
          `  }`,
          `}`,
          ``,
        ];

  return [
    `# Generated by Juanie schema management`,
    `# Plan: ${input.planId}`,
    `# Kind: ${input.planKind}`,
    `# Tool: ${input.tool}`,
    `# Database: ${input.databaseName}`,
    ``,
    ...envBlock,
  ].join('\n');
}

function buildAtlasScriptContent(
  input: SchemaRepairArtifactInput,
  atlasConfigPath: string
): string {
  const schemaFilePath = `.juanie/schema-repair/${input.planId}.schema.sql`;
  const migrationName =
    input.planKind === 'adopt_current_db'
      ? `baseline_${input.planId.slice(0, 8)}`
      : `repair_${input.planId.slice(0, 8)}`;

  const installLines =
    input.tool === 'drizzle'
      ? [
          `if [ -f bun.lockb ] || [ -f bun.lock ]; then`,
          `  bun install --frozen-lockfile`,
          `elif [ -f pnpm-lock.yaml ]; then`,
          `  pnpm install --frozen-lockfile`,
          `elif [ -f yarn.lock ]; then`,
          `  yarn install --immutable`,
          `elif [ -f package-lock.json ]; then`,
          `  npm ci`,
          `else`,
          `  npm install`,
          `fi`,
          ``,
          `DRIZZLE_CONFIG="${'$'}{DRIZZLE_CONFIG:-$(ls drizzle.config.ts drizzle.config.mjs drizzle.config.js drizzle.config.cjs 2>/dev/null | head -n 1)}"`,
          `if [ -z "${'$'}DRIZZLE_CONFIG" ]; then`,
          `  echo "Unable to locate drizzle config" >&2`,
          `  exit 1`,
          `fi`,
          `npx drizzle-kit export --config "${'$'}DRIZZLE_CONFIG" > "${schemaFilePath}"`,
          ``,
        ]
      : [];

  return [
    `#!/usr/bin/env bash`,
    `set -euo pipefail`,
    ``,
    `# Generated by Juanie schema management.`,
    `# Prefer Atlas for real migration generation instead of editing scaffold SQL by hand.`,
    `# Required env: ATLAS_DEV_URL and${input.tool === 'sql' ? ' ATLAS_SRC_URL' : ''} optional ATLAS_IMAGE`,
    ``,
    ...installLines,
    `ATLAS_IMAGE="\${ATLAS_IMAGE:-arigaio/atlas:latest}"`,
    `if command -v atlas >/dev/null 2>&1; then`,
    `  atlas migrate diff "${migrationName}" --env repair --config "file://${atlasConfigPath}"`,
    `else`,
    `  docker run --rm \\`,
    `    -v "$PWD:/workspace" \\`,
    `    -w /workspace \\`,
    `    -e ATLAS_DEV_URL="${'$'}{ATLAS_DEV_URL:-}" \\`,
    input.tool === 'sql' ? `    -e ATLAS_SRC_URL="${'$'}{ATLAS_SRC_URL:-}" \\` : '',
    `    "$ATLAS_IMAGE" migrate diff "${migrationName}" \\`,
    `    --env repair \\`,
    `    --config "file://${atlasConfigPath}"`,
    `fi`,
    ``,
  ]
    .filter(Boolean)
    .join('\n');
}

function buildScaffoldHeading(input: SchemaRepairArtifactInput): string[] {
  const modeSummary =
    input.planKind === 'adopt_current_db'
      ? 'baseline scaffold'
      : input.planKind === 'repair_pr_required'
        ? 'repair scaffold'
        : 'investigation scaffold';

  return [
    `-- Generated by Juanie schema management`,
    `-- Plan ID: ${input.planId}`,
    `-- Plan kind: ${input.planKind}`,
    `-- State status: ${input.stateStatus}`,
    `-- Database: ${input.databaseName}`,
    `-- Mode: ${modeSummary}`,
    `-- Expected version: ${input.expectedVersion ?? 'unknown'}`,
    `-- Actual version: ${input.actualVersion ?? 'unknown'}`,
    `-- Title: ${input.title}`,
    `-- Summary: ${input.summary}`,
    `-- Replace this scaffold before merge.`,
    ``,
  ];
}

export function buildSchemaRepairRuntimeArtifacts(
  input: SchemaRepairArtifactInput
): SchemaRepairRuntimeArtifacts {
  const atlasConfigPath = `.juanie/schema-repair/${input.planId}.atlas.hcl`;
  const atlasScriptPath = `.juanie/schema-repair/${input.planId}.atlas.sh`;

  return {
    files: {
      [atlasConfigPath]: buildAtlasConfigContent(input),
      [atlasScriptPath]: buildAtlasScriptContent(input, atlasConfigPath),
    },
    atlasConfigPath,
    atlasScriptPath,
  };
}

export function buildSchemaRepairArtifacts(
  input: SchemaRepairArtifactInput
): GeneratedSchemaRepairArtifacts {
  const files: Record<string, string> = {};
  const generatedFiles: string[] = [];

  const needsMigrationScaffold =
    input.migrationPath &&
    ['drizzle', 'sql'].includes(input.tool) &&
    ['repair_pr_required', 'adopt_current_db'].includes(input.planKind);

  if (!needsMigrationScaffold || !input.migrationPath) {
    return {
      files,
      generatedFiles,
      migrationTag: null,
    };
  }

  const stemPrefix =
    input.planKind === 'adopt_current_db' ? 'juanie_schema_baseline' : 'juanie_schema_repair';
  const stem = `${stemPrefix}_${input.planId.slice(0, 8)}`;
  const migrationTag = buildNextMigrationTag(input.existingMigrationNames, stem);
  const filePath = `${input.migrationPath}/${migrationTag}.sql`;
  const message = buildFailureScaffoldMessage(input);
  const heading = buildScaffoldHeading(input);

  const failureSql =
    input.databaseType === 'postgresql'
      ? [
          ...heading,
          `DO $$`,
          `BEGIN`,
          `  RAISE EXCEPTION '${message.replace(/'/g, "''")}';`,
          `END $$;`,
          ``,
        ].join('\n')
      : input.databaseType === 'mysql'
        ? [
            ...heading,
            `SIGNAL SQLSTATE '45000'`,
            `  SET MESSAGE_TEXT = '${message.replace(/'/g, "''")}';`,
            ``,
          ].join('\n')
        : `${heading.join('\n')}JUANIE_REPAIR_SCAFFOLD_REPLACE_ME;\n`;

  if (input.tool === 'sql') {
    return {
      files: {
        ...files,
        [filePath]: failureSql,
      },
      generatedFiles: [...generatedFiles, filePath],
      migrationTag,
    };
  }

  const journalPath = `${input.migrationPath}/meta/_journal.json`;

  return {
    files: {
      ...files,
      [filePath]: failureSql,
      [journalPath]: appendDrizzleJournalEntry(input.journalContent, migrationTag, Date.now()),
    },
    generatedFiles: [...generatedFiles, filePath, journalPath],
    migrationTag,
  };
}
