import { eq } from 'drizzle-orm';
import { createAuditLog } from '@/lib/audit';
import { db } from '@/lib/db';
import type { EnvironmentSchemaStateStatus } from '@/lib/db/schema';
import { projects, schemaRepairPlans } from '@/lib/db/schema';
import {
  gateway,
  getTeamIntegrationSession,
} from '@/lib/integrations/service/integration-control-plane';
import {
  fetchMigrationFilesFromRepoPath,
  readRepositoryFileFromRepoPath,
} from '@/lib/migrations/fetch';
import { resolveMigrationPath } from '@/lib/migrations/path';
import { resolveSchemaManagementSpec } from '@/lib/schema-management/inspect';
import { getEnvironmentSchemaStateLabel } from '@/lib/schema-management/presentation';
import { buildSchemaRepairArtifacts } from '@/lib/schema-management/review-request-helpers';

function sanitizeBranchSegment(value: string): string {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 40);
}

function buildSchemaRepairReviewBody(input: {
  projectName: string;
  databaseName: string;
  plan: {
    stateStatus: EnvironmentSchemaStateStatus;
    riskLevel: string;
    kind: string;
    summary: string;
    nextActionLabel: string | null;
    expectedVersion: string | null;
    actualVersion: string | null;
    steps: string[];
  };
}) {
  return [
    `# Schema Repair Plan`,
    ``,
    `项目: ${input.projectName}`,
    `数据库: ${input.databaseName}`,
    `状态: ${getEnvironmentSchemaStateLabel(input.plan.stateStatus)}`,
    `风险: ${input.plan.riskLevel}`,
    ``,
    `## 摘要`,
    input.plan.summary,
    ``,
    `## 下一步`,
    input.plan.nextActionLabel ?? '请按下列步骤执行。',
    ``,
    `## Steps`,
    ...input.plan.steps.map((step, index) => `${index + 1}. ${step}`),
    ``,
    `## Metadata`,
    `- kind: ${input.plan.kind}`,
    `- expectedVersion: ${input.plan.expectedVersion ?? 'unknown'}`,
    `- actualVersion: ${input.plan.actualVersion ?? 'unknown'}`,
    ``,
    `> This review request was generated by Juanie schema management.`,
  ].join('\n');
}

export async function createSchemaRepairReviewRequest(input: {
  projectId: string;
  planId: string;
  userId: string;
}) {
  const project = await db.query.projects.findFirst({
    where: eq(projects.id, input.projectId),
    with: {
      repository: true,
    },
  });

  if (!project?.repository) {
    throw new Error('项目缺少仓库绑定，无法生成修复 PR');
  }

  const plan = await db.query.schemaRepairPlans.findFirst({
    where: eq(schemaRepairPlans.id, input.planId),
    with: {
      database: true,
      environment: true,
    },
  });

  if (!plan || plan.projectId !== input.projectId) {
    throw new Error('修复计划不存在');
  }

  if (!['repair_pr_required', 'adopt_current_db', 'manual_investigation'].includes(plan.kind)) {
    throw new Error('当前修复计划不需要生成 PR');
  }

  const session = await getTeamIntegrationSession({
    teamId: project.teamId,
    actingUserId: input.userId,
    requiredCapabilities: ['write_repo'],
  });

  const baseBranch = project.repository.defaultBranch || 'main';
  const branchName = [
    'schema-repair',
    sanitizeBranchSegment(plan.database?.name ?? 'database'),
    plan.id.slice(0, 8),
  ].join('/');
  const filePath = `.juanie/schema-repair/${plan.id}.md`;
  const body = buildSchemaRepairReviewBody({
    projectName: project.name,
    databaseName: plan.database?.name ?? 'database',
    plan: {
      kind: plan.kind,
      stateStatus: plan.stateStatus,
      riskLevel: plan.riskLevel,
      summary: plan.summary,
      nextActionLabel: plan.nextActionLabel,
      expectedVersion: plan.expectedVersion,
      actualVersion: plan.actualVersion,
      steps: Array.isArray(plan.steps) ? (plan.steps as string[]) : [],
    },
  });
  const spec = await resolveSchemaManagementSpec({
    projectId: input.projectId,
    databaseId: plan.databaseId,
  });
  const migrationPath =
    spec && plan.kind !== 'manual_investigation'
      ? resolveMigrationPath(spec.specification, spec.database.type)
      : null;
  const migrationFiles =
    spec && migrationPath
      ? await fetchMigrationFilesFromRepoPath(
          spec.specification.projectId,
          migrationPath,
          baseBranch
        )
      : [];
  const journalContent =
    spec?.specification.tool === 'drizzle' && migrationPath
      ? await readRepositoryFileFromRepoPath(
          spec.specification.projectId,
          `${migrationPath}/meta/_journal.json`,
          baseBranch
        )
      : null;
  const generatedArtifacts =
    spec && migrationPath
      ? buildSchemaRepairArtifacts({
          tool: spec.specification.tool,
          databaseType: spec.database.type,
          migrationPath,
          existingMigrationNames:
            spec.specification.tool === 'drizzle'
              ? migrationFiles.map((file) => file.name)
              : migrationFiles.map((file) => file.name),
          journalContent,
          planId: plan.id,
          title: plan.title,
          summary: plan.summary,
        })
      : {
          files: {},
          generatedFiles: [],
          migrationTag: null,
        };

  try {
    await gateway.createBranch(session, {
      repoFullName: project.repository.fullName,
      branch: branchName,
      fromBranch: baseBranch,
    });

    await gateway.pushFiles(session, {
      repoFullName: project.repository.fullName,
      branch: branchName,
      message: `chore: add schema repair plan for ${plan.database?.name ?? 'database'}`,
      files: {
        [filePath]: body,
        ...generatedArtifacts.files,
      },
    });

    const review = await gateway.createReviewRequest(session, {
      repoFullName: project.repository.fullName,
      title: `Schema repair: ${plan.database?.name ?? 'database'}`,
      body,
      headBranch: branchName,
      baseBranch,
      draft: true,
    });

    const [updated] = await db
      .update(schemaRepairPlans)
      .set({
        status: 'review_opened',
        branchName,
        reviewNumber: review.number,
        reviewUrl: review.webUrl,
        generatedFiles: [filePath, ...generatedArtifacts.generatedFiles],
        errorMessage: null,
        updatedAt: new Date(),
      })
      .where(eq(schemaRepairPlans.id, plan.id))
      .returning();

    await createAuditLog({
      teamId: project.teamId,
      userId: input.userId,
      action: 'project.updated',
      resourceType: 'project',
      resourceId: project.id,
      metadata: {
        schemaAction: 'create_repair_review_request',
        databaseId: plan.databaseId,
        planId: plan.id,
        branchName,
        reviewUrl: review.webUrl,
      },
    });

    return {
      review,
      plan: updated,
    };
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    await db
      .update(schemaRepairPlans)
      .set({
        status: 'failed',
        branchName,
        errorMessage: message,
        updatedAt: new Date(),
      })
      .where(eq(schemaRepairPlans.id, plan.id));
    throw error;
  }
}
