import { drizzleSchemaConfigCandidates } from '@/lib/migrations/schema-source';

export interface SchemaRepairRuntimeArtifacts {
  files: Record<string, string>;
  atlasConfigPath: string;
  atlasScriptPath: string;
}

interface SchemaRepairArtifactInput {
  provider: 'github' | 'gitlab' | 'gitlab-self-hosted';
  tool: 'atlas' | 'drizzle' | 'sql' | 'prisma' | 'knex' | 'typeorm' | 'custom';
  databaseType: 'postgresql' | 'mysql' | 'redis' | 'mongodb';
  migrationPath: string | null;
  planId: string;
  title: string;
  summary: string;
  planKind:
    | 'no_action'
    | 'run_release_migrations'
    | 'mark_aligned'
    | 'repair_pr_required'
    | 'adopt_current_db'
    | 'manual_investigation';
  stateStatus: string;
  databaseName: string;
  expectedVersion: string | null;
  actualVersion: string | null;
  sourceConfigPath?: string | null;
}

function buildAtlasConfigContent(input: SchemaRepairArtifactInput): string {
  const schemaFilePath = `.juanie/schema-repair/${input.planId}.schema.sql`;
  const migrationDir =
    input.tool === 'drizzle' ? '.juanie/schema-repair/generated' : input.migrationPath;
  const envBlock =
    input.tool === 'drizzle'
      ? [
          `env "repair" {`,
          `  src = "file://${schemaFilePath}"`,
          `  dev = env("ATLAS_DEV_URL")`,
          `  migration {`,
          `    dir = "file://${migrationDir}"`,
          `  }`,
          `}`,
          ``,
        ]
      : [
          `env "repair" {`,
          `  src = env("ATLAS_SRC_URL")`,
          `  dev = env("ATLAS_DEV_URL")`,
          `  migration {`,
          `    dir = "file://${migrationDir}"`,
          `  }`,
          `}`,
          ``,
        ];

  return [
    `# Generated by Juanie schema management`,
    `# Plan: ${input.planId}`,
    `# Kind: ${input.planKind}`,
    `# Tool: ${input.tool}`,
    `# Database: ${input.databaseName}`,
    ``,
    ...envBlock,
  ].join('\n');
}

function buildAtlasScriptContent(
  input: SchemaRepairArtifactInput,
  atlasConfigPath: string
): string {
  const schemaFilePath = `.juanie/schema-repair/${input.planId}.schema.sql`;
  const migrationName =
    input.planKind === 'adopt_current_db'
      ? `baseline_${input.planId.slice(0, 8)}`
      : `repair_${input.planId.slice(0, 8)}`;

  const installLines =
    input.tool === 'drizzle'
      ? [
          `if [ -f bun.lockb ] || [ -f bun.lock ]; then`,
          `  bun install --frozen-lockfile`,
          `elif [ -f pnpm-lock.yaml ]; then`,
          `  pnpm install --frozen-lockfile`,
          `elif [ -f yarn.lock ]; then`,
          `  yarn install --immutable`,
          `elif [ -f package-lock.json ]; then`,
          `  npm ci`,
          `else`,
          `  npm install`,
          `fi`,
          ``,
          input.sourceConfigPath
            ? `DRIZZLE_CONFIG="${'$'}{DRIZZLE_CONFIG:-${input.sourceConfigPath}}"`
            : `DRIZZLE_CONFIG="${'$'}{DRIZZLE_CONFIG:-$(find . -path ./node_modules -prune -o -path ./.git -prune -o \\( ${drizzleSchemaConfigCandidates
                .map((candidate) => `-name '${candidate}'`)
                .join(' -o ')} \\) -print | sed 's#^./##' | sort | head -n 1)}"`,
          `if [ -z "${'$'}DRIZZLE_CONFIG" ]; then`,
          `  echo "Unable to locate drizzle config" >&2`,
          `  exit 1`,
          `fi`,
          `npx drizzle-kit export --config "${'$'}DRIZZLE_CONFIG" > "${schemaFilePath}"`,
          ``,
        ]
      : [];

  return [
    `#!/usr/bin/env bash`,
    `set -euo pipefail`,
    ``,
    `# Generated by Juanie schema management.`,
    `# Prefer Atlas for real migration generation instead of editing scaffold SQL by hand.`,
    `# Required env: ATLAS_DEV_URL and${input.tool === 'sql' ? ' ATLAS_SRC_URL' : ''} optional ATLAS_IMAGE`,
    ``,
    ...installLines,
    `ATLAS_IMAGE="\${ATLAS_IMAGE:-arigaio/atlas:latest}"`,
    `if command -v atlas >/dev/null 2>&1; then`,
    `  atlas migrate diff "${migrationName}" --env repair --config "file://${atlasConfigPath}"`,
    `else`,
    `  docker run --rm \\`,
    `    -v "$PWD:/workspace" \\`,
    `    -w /workspace \\`,
    `    -e ATLAS_DEV_URL="${'$'}{ATLAS_DEV_URL:-}" \\`,
    input.tool === 'sql' ? `    -e ATLAS_SRC_URL="${'$'}{ATLAS_SRC_URL:-}" \\` : '',
    `    "$ATLAS_IMAGE" migrate diff "${migrationName}" \\`,
    `    --env repair \\`,
    `    --config "file://${atlasConfigPath}"`,
    `fi`,
    ``,
  ]
    .filter(Boolean)
    .join('\n');
}

export function buildSchemaRepairRuntimeArtifacts(
  input: SchemaRepairArtifactInput
): SchemaRepairRuntimeArtifacts {
  const atlasConfigPath = `.juanie/schema-repair/${input.planId}.atlas.hcl`;
  const atlasScriptPath = `.juanie/schema-repair/${input.planId}.atlas.sh`;

  return {
    files: {
      [atlasConfigPath]: buildAtlasConfigContent(input),
      [atlasScriptPath]: buildAtlasScriptContent(input, atlasConfigPath),
    },
    atlasConfigPath,
    atlasScriptPath,
  };
}
