export interface GeneratedSchemaRepairArtifacts {
  files: Record<string, string>;
  generatedFiles: string[];
  migrationTag: string | null;
}

function parseNumericPrefix(value: string): number | null {
  const match = value.match(/^(\d+)_/u);
  if (!match?.[1]) {
    return null;
  }

  return Number.parseInt(match[1], 10);
}

export function buildNextMigrationTag(existingNames: string[], stem: string): string {
  const parsed = existingNames
    .map((name) => name.replace(/\.(sql|js)$/u, ''))
    .map((name) => ({
      name,
      prefix: parseNumericPrefix(name),
    }))
    .filter((item) => item.prefix !== null);

  const maxPrefix = parsed.reduce((current, item) => Math.max(current, item.prefix ?? 0), -1);
  const width = parsed.reduce((current, item) => {
    const match = item.name.match(/^(\d+)_/u);
    return Math.max(current, match?.[1]?.length ?? 4);
  }, 4);

  return `${String(maxPrefix + 1).padStart(width, '0')}_${stem}`;
}

export function appendDrizzleJournalEntry(
  journalContent: string | null | undefined,
  tag: string,
  when: number
): string {
  const journal = journalContent
    ? (JSON.parse(journalContent) as {
        version?: string;
        dialect?: string;
        entries?: Array<{
          idx?: unknown;
          version?: unknown;
          when?: unknown;
          tag?: unknown;
          breakpoints?: unknown;
        }>;
      })
    : {};

  const version = typeof journal.version === 'string' ? journal.version : '7';
  const dialect = typeof journal.dialect === 'string' ? journal.dialect : 'postgresql';
  const existingEntries = Array.isArray(journal.entries) ? journal.entries : [];
  const nextIdx =
    existingEntries.reduce((current, entry) => {
      const idx = typeof entry?.idx === 'number' ? entry.idx : -1;
      return Math.max(current, idx);
    }, -1) + 1;

  const next = {
    version,
    dialect,
    entries: [
      ...existingEntries,
      {
        idx: nextIdx,
        version,
        when,
        tag,
        breakpoints: true,
      },
    ],
  };

  return `${JSON.stringify(next, null, 2)}\n`;
}

function buildFailureScaffoldMessage(input: {
  planId: string;
  title: string;
  summary: string;
}): string {
  return [
    `Generated by Juanie schema management.`,
    `Plan: ${input.planId}`,
    `Title: ${input.title}`,
    `Summary: ${input.summary}`,
    `Replace this scaffold with the real repair migration before merge.`,
  ].join(' | ');
}

export function buildSchemaRepairArtifacts(input: {
  tool: 'drizzle' | 'sql' | 'prisma' | 'knex' | 'typeorm' | 'custom';
  databaseType: 'postgresql' | 'mysql' | 'redis' | 'mongodb';
  migrationPath: string | null;
  existingMigrationNames: string[];
  journalContent?: string | null;
  planId: string;
  title: string;
  summary: string;
}): GeneratedSchemaRepairArtifacts {
  if (!input.migrationPath || !['drizzle', 'sql'].includes(input.tool)) {
    return {
      files: {},
      generatedFiles: [],
      migrationTag: null,
    };
  }

  const stem = `juanie_schema_repair_${input.planId.slice(0, 8)}`;
  const migrationTag = buildNextMigrationTag(input.existingMigrationNames, stem);
  const filePath = `${input.migrationPath}/${migrationTag}.sql`;
  const message = buildFailureScaffoldMessage({
    planId: input.planId,
    title: input.title,
    summary: input.summary,
  });

  const failureSql =
    input.databaseType === 'postgresql'
      ? [
          `DO $$`,
          `BEGIN`,
          `  RAISE EXCEPTION '${message.replace(/'/g, "''")}';`,
          `END $$;`,
          ``,
        ].join('\n')
      : input.databaseType === 'mysql'
        ? [
            `SIGNAL SQLSTATE '45000'`,
            `  SET MESSAGE_TEXT = '${message.replace(/'/g, "''")}';`,
            ``,
          ].join('\n')
        : `JUANIE_REPAIR_SCAFFOLD_REPLACE_ME;\n`;

  if (input.tool === 'sql') {
    return {
      files: {
        [filePath]: failureSql,
      },
      generatedFiles: [filePath],
      migrationTag,
    };
  }

  const journalPath = `${input.migrationPath}/meta/_journal.json`;

  return {
    files: {
      [filePath]: failureSql,
      [journalPath]: appendDrizzleJournalEntry(input.journalContent, migrationTag, Date.now()),
    },
    generatedFiles: [filePath, journalPath],
    migrationTag,
  };
}
