import { eq } from 'drizzle-orm';
import { createAuditLog } from '@/lib/audit';
import { db } from '@/lib/db';
import type { EnvironmentSchemaStateStatus, SchemaRepairPlanKind } from '@/lib/db/schema';
import { schemaRepairPlans } from '@/lib/db/schema';
import { gateway } from '@/lib/integrations/service/integration-control-plane';
import { getRepositoryDefaultBranch } from '@/lib/projects/refs';
import { publishSchemaRepairRealtimeSnapshot } from '@/lib/realtime/schema-repairs';
import { getEnvironmentSchemaStateLabel } from '@/lib/schema-management/presentation';
import {
  loadLatestSchemaRepairGeneratedArtifacts,
  loadSchemaRepairPlanExecutionContext,
  requireSchemaRepairRepositorySession,
} from '@/lib/schema-management/repair-context';
import { toPersistedSchemaRepairPlan } from '@/lib/schema-management/repair-plan';

function sanitizeBranchSegment(value: string): string {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 40);
}

function buildSchemaRepairReviewBody(input: {
  projectName: string;
  databaseName: string;
  plan: {
    stateStatus: EnvironmentSchemaStateStatus;
    riskLevel: string;
    kind: string;
    summary: string;
    nextActionLabel: string | null;
    expectedVersion: string | null;
    actualVersion: string | null;
    steps: string[];
  };
}) {
  return [
    `# Schema Repair Plan`,
    ``,
    `项目: ${input.projectName}`,
    `数据库: ${input.databaseName}`,
    `状态: ${getEnvironmentSchemaStateLabel(input.plan.stateStatus)}`,
    `风险: ${input.plan.riskLevel}`,
    ``,
    `## 摘要`,
    input.plan.summary,
    ``,
    `## 下一步`,
    input.plan.nextActionLabel ?? '请按下列步骤执行。',
    ``,
    `## Steps`,
    ...input.plan.steps.map((step, index) => `${index + 1}. ${step}`),
    ``,
    `## Metadata`,
    `- kind: ${input.plan.kind}`,
    `- expectedVersion: ${input.plan.expectedVersion ?? 'unknown'}`,
    `- actualVersion: ${input.plan.actualVersion ?? 'unknown'}`,
    ``,
    `## Execution`,
    `- Atlas execution runs inside Juanie, not in repository CI.`,
    `- This PR only carries reviewable repair changes.`,
    ``,
    `> This review request was generated by Juanie schema management.`,
  ].join('\n');
}

export function resolveSchemaRepairReviewFiles(input: {
  body: string;
  fallbackReviewFilePath: string;
  generatedArtifacts: {
    files: Record<string, string>;
    generatedFiles: string[];
  };
}): {
  files: Record<string, string>;
  generatedFiles: string[];
} {
  if (Object.keys(input.generatedArtifacts.files).length > 0) {
    return {
      files: input.generatedArtifacts.files,
      generatedFiles: input.generatedArtifacts.generatedFiles,
    };
  }

  return {
    files: {
      [input.fallbackReviewFilePath]: input.body,
    },
    generatedFiles: [input.fallbackReviewFilePath],
  };
}

function canCreateReviewWithoutDraft(kind: SchemaRepairPlanKind): boolean {
  return kind === 'manual_investigation';
}

export async function createSchemaRepairReviewRequest(input: {
  projectId: string;
  planId: string;
  userId: string;
}) {
  const { project, plan } = await loadSchemaRepairPlanExecutionContext({
    projectId: input.projectId,
    planId: input.planId,
  });

  if (!['repair_pr_required', 'adopt_current_db', 'manual_investigation'].includes(plan.kind)) {
    throw new Error('当前修复计划不需要生成 PR');
  }

  const session = await requireSchemaRepairRepositorySession({
    teamId: project.teamId,
    userId: input.userId,
    requiredCapabilities: ['write_repo'],
  });

  const baseBranch = getRepositoryDefaultBranch(project.repository);
  const branchName = [
    'schema-repair',
    sanitizeBranchSegment(plan.database?.name ?? 'database'),
    plan.id.slice(0, 8),
  ].join('/');
  const fallbackReviewFilePath = `.juanie/schema-repair/${plan.id}.md`;
  const body = buildSchemaRepairReviewBody({
    projectName: project.name,
    databaseName: plan.database?.name ?? 'database',
    plan: {
      kind: plan.kind,
      stateStatus: plan.stateStatus,
      riskLevel: plan.riskLevel,
      summary: plan.summary,
      nextActionLabel: plan.nextActionLabel,
      expectedVersion: plan.expectedVersion,
      actualVersion: plan.actualVersion,
      steps: Array.isArray(plan.steps) ? (plan.steps as string[]) : [],
    },
  });
  const generatedArtifacts = await loadLatestSchemaRepairGeneratedArtifacts(plan.id);

  if (
    !canCreateReviewWithoutDraft(plan.kind) &&
    Object.keys(generatedArtifacts.files).length === 0
  ) {
    throw new Error('请先生成修复草案并确认迁移详情，再创建 PR');
  }

  const reviewPayload = resolveSchemaRepairReviewFiles({
    body,
    fallbackReviewFilePath,
    generatedArtifacts,
  });

  try {
    await gateway.createBranch(session, {
      repoFullName: project.repository.fullName,
      branch: branchName,
      fromBranch: baseBranch,
    });

    await gateway.pushFiles(session, {
      repoFullName: project.repository.fullName,
      branch: branchName,
      message: `chore: add schema repair plan for ${plan.database?.name ?? 'database'}`,
      files: reviewPayload.files,
    });

    const review = await gateway.createReviewRequest(session, {
      repoFullName: project.repository.fullName,
      title: `Schema repair: ${plan.database?.name ?? 'database'}`,
      body,
      headBranch: branchName,
      baseBranch,
      draft: false,
    });

    const [updated] = await db
      .update(schemaRepairPlans)
      .set({
        status: 'review_opened',
        branchName,
        reviewNumber: review.number,
        reviewUrl: review.webUrl,
        reviewState: review.state,
        reviewStateLabel: review.stateLabel,
        reviewSyncedAt: new Date(),
        atlasExecutionStatus: 'idle',
        atlasExecutionStartedAt: null,
        atlasExecutionFinishedAt: null,
        atlasExecutionLog: null,
        generatedFiles: reviewPayload.generatedFiles,
        errorMessage: null,
        updatedAt: new Date(),
      })
      .where(eq(schemaRepairPlans.id, plan.id))
      .returning();

    await createAuditLog({
      teamId: project.teamId,
      userId: input.userId,
      action: 'project.updated',
      resourceType: 'project',
      resourceId: project.id,
      metadata: {
        schemaAction: 'create_repair_review_request',
        databaseId: plan.databaseId,
        planId: plan.id,
        branchName,
        reviewUrl: review.webUrl,
      },
    });

    await publishSchemaRepairRealtimeSnapshot({
      projectId: input.projectId,
      databaseId: plan.databaseId,
    });

    return {
      review,
      plan: toPersistedSchemaRepairPlan(updated),
    };
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    await db
      .update(schemaRepairPlans)
      .set({
        status: 'failed',
        branchName,
        errorMessage: message,
        updatedAt: new Date(),
      })
      .where(eq(schemaRepairPlans.id, plan.id));

    await publishSchemaRepairRealtimeSnapshot({
      projectId: input.projectId,
      databaseId: plan.databaseId,
    });
    throw error;
  }
}
